name: Blog Post Idea
description: Track a blog post topic or idea for future writing
title: "[Post] "
labels: ["content", "blog-post"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to capture blog post ideas and track their progress.

  - type: input
    id: title
    attributes:
      label: Working Title
      description: A working title for the post (can be refined later)
      placeholder: "How to Build X with Y"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Primary category for the post
      options:
        - Security & Forensics
        - Systems Programming
        - Infrastructure & DevOps
        - Development & Tutorials
        - AI & Automation
        - Hardware & Embedded
        - Career & Personal
        - Other
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated list of tags
      placeholder: "rust, ebpf, linux, tutorial"

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of what the post will cover
      placeholder: |
        What's the main point?
        Who is the target audience?
        What will readers learn?
    validations:
      required: true

  - type: textarea
    id: outline
    attributes:
      label: Outline (Optional)
      description: Rough outline or key points to cover
      placeholder: |
        - Introduction
        - Section 1: ...
        - Section 2: ...
        - Conclusion

  - type: textarea
    id: resources
    attributes:
      label: Resources & References
      description: Links, papers, docs, or other references
      placeholder: |
        - https://example.com/relevant-article
        - Book: "Relevant Book Title"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How soon do you want to write this?
      options:
        - High - Write soon
        - Medium - On the backlog
        - Low - Someday maybe
      default: 1

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much work will this post require?
      options:
        - Small - Quick post (<1 hour)
        - Medium - Standard post (1-3 hours)
        - Large - Deep dive (3+ hours)
        - Research Required - Unknown scope
      default: 1

  - type: checkboxes
    id: checklist
    attributes:
      label: Progress Checklist
      description: Track writing progress
      options:
        - label: Research complete
        - label: Outline finalized
        - label: First draft written
        - label: Code examples tested
        - label: Images/diagrams created
        - label: Post reviewed/edited
        - label: Published
